# prospector configuration file

---
output-format: grouped
strictness: veryhigh
doc-warnings: true
test-warnings: true
member-warnings: true

frosted:
  run: false

pyroma:
  run: false

mypy:
  run: false

pydocroma:
  run: true

pep8:
  run: true
  disable: [
    E501,  # Line-length, already controlled by pylint
  ]

pep257:
  run: true
    # see http://pep257.readthedocs.io/en/latest/error_codes.html
  disable: [
    D203,  # 1 blank line required before class docstring
           # conflicts with D0211, No blank lines allowed before class docstring
  ]
